# Generated by Django 4.2.4 on 2023-08-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0003_post_alter_product_image_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=200)),
                ('advice_text', models.CharField(max_length=350)),
                ('published_on', models.DateField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='chat_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('added_on', models.DateField(verbose_name='date added')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_order.chat_post')),
            ],
        ),
    ]
