# Generated by Django 4.2.4 on 2023-08-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0004_chat_post_chat_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat_comment',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat_post',
            name='advice_text',
            field=models.TextField(),
        ),
    ]
