# Generated by Django 4.2.4 on 2023-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0005_chat_comment_author_alter_chat_comment_added_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_comment',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
